#ifndef CLIENT_INCLUDE_ERROR_EXIT_CODES_H_
#define CLIENT_INCLUDE_ERROR_EXIT_CODES_H_

#define BAD_ARGS 5
#define ERROR -1
#define CANT_CREATE_FIFO 6
#define CANT_OPEN_FIFO 7

#endif  // CLIENT_INCLUDE_ERROR_EXIT_CODES_H_
