#ifndef SERVER_INCLUDE_ERROR_EXIT_CODES_H_
#define SERVER_INCLUDE_ERROR_EXIT_CODES_H_

#define BAD_ARGS 5
#define ERROR -1
#define CANT_CREATE_FIFO 6
#define CANT_OPEN_FIFO 7

#endif  // SERVER_INCLUDE_ERROR_EXIT_CODES_H_
